#!/usr/bin/env bun
// Builds generated/art.ts from the private bunny art, if it's here.
//
// The bunny faces are licensed (Envato Elements) and never committed: they live in the gitignored
// private/ folder (bunny-1…10.png, favicon.ico, icon-32.png, apple-touch-icon.png). With them,
// the module inlines them as data URIs, so the app, the compiled binary and the website all get
// them the same way. Without them it exports nulls, and every bunny image is simply left out.
//
//   bun packages/brand/scripts/generate.ts             art if present, else none
//   bun packages/brand/scripts/generate.ts --require   fail without the art (release builds)
//
// With the art, it also writes the website's icon files (apps/web/app/icon.png, apple-icon.png,
// favicon.ico) and social preview (opengraph-image.png, twitter-image.png, + .alt.txt), all
// gitignored. Without the art those files are removed, and the site's metadata goes text-only.
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const BRAND = resolve(import.meta.dir, "..");
const PRIVATE = join(BRAND, "private");
const OUT = join(BRAND, "generated", "art.ts");
const WEB_APP = resolve(BRAND, "..", "..", "apps", "web", "app");
const FACES = Array.from({ length: 10 }, (_, i) => `bunny-${i + 1}.png`);
const ICONS = { favicon: "favicon.ico", icon32: "icon-32.png", appleTouch: "apple-touch-icon.png", og: "og.png" };
/** The social preview's alt text (Next reads it from a file next to the image). */
const OG_ALT = "PR Bunny: a second pair of ears on every pull request. Free AI code review with the Claude Code or Codex you already use.";

const required = process.argv.includes("--require") || process.env.PR_BUNNY_REQUIRE_ART === "1";
const missing = [...FACES, ...Object.values(ICONS)].filter((f) => !existsSync(join(PRIVATE, f)));
const hasArt = missing.length === 0;

if (!hasArt && required) {
  console.error(
    `✗ The bunny art is required for this build but isn't in packages/brand/private/.\n` +
      `  Missing: ${missing.join(", ")}\n` +
      `  It's licensed and kept out of git: copy it in from the private brand store, then build again.`,
  );
  process.exit(1);
}

const dataUri = (file: string, type: string) => `data:${type};base64,${readFileSync(join(PRIVATE, file)).toString("base64")}`;
const lit = (v: string | null) => (v === null ? "null" : JSON.stringify(v));

const body = hasArt
  ? `export const HAS_ART = true;

/** The ten faces, as data URIs: faces[0] is bunny-1. */
export const faces: readonly string[] | null = [
${FACES.map((f) => `  ${lit(dataUri(f, "image/png"))},`).join("\n")}
];

/** 32×32 favicon and 180×180 apple-touch icon. */
export const icon32: string | null = ${lit(dataUri(ICONS.icon32, "image/png"))};
export const appleTouchIcon: string | null = ${lit(dataUri(ICONS.appleTouch, "image/png"))};
`
  : `export const HAS_ART = false;

/** No art in packages/brand/private/: bunny images are left out of this build. */
export const faces: readonly string[] | null = null;
export const icon32: string | null = null;
export const appleTouchIcon: string | null = null;
`;

mkdirSync(join(BRAND, "generated"), { recursive: true });
const text = `// Generated by packages/brand/scripts/generate.ts. Don't edit; not committed.\n${body}`;
// Only rewrite when it changed, so dev servers don't reload for nothing.
if (!existsSync(OUT) || readFileSync(OUT, "utf8") !== text) writeFileSync(OUT, text);

// The website reads its icons from files in app/ (Next's convention).
if (existsSync(WEB_APP)) {
  const webIcons: Record<string, string> = {
    "icon.png": ICONS.icon32,
    "apple-icon.png": ICONS.appleTouch,
    "favicon.ico": ICONS.favicon,
    "opengraph-image.png": ICONS.og,
    "twitter-image.png": ICONS.og,
  };
  for (const [name, src] of Object.entries(webIcons)) {
    const dest = join(WEB_APP, name);
    if (hasArt) {
      const data = readFileSync(join(PRIVATE, src));
      if (!existsSync(dest) || !readFileSync(dest).equals(data)) writeFileSync(dest, data);
    } else rmSync(dest, { force: true });
  }
  for (const name of ["opengraph-image.alt.txt", "twitter-image.alt.txt"]) {
    const dest = join(WEB_APP, name);
    if (hasArt) {
      if (!existsSync(dest) || readFileSync(dest, "utf8") !== OG_ALT) writeFileSync(dest, OG_ALT);
    } else rmSync(dest, { force: true });
  }
}

console.log(hasArt ? "✓ bunny art included" : "○ no bunny art (packages/brand/private/ is empty); building without images");
