#!/usr/bin/env bun
// Writes generated/icons.ts: which Hugeicons PR Bunny draws with.
//
// Free (the default, and what the public repo builds with): @hugeicons/core-free-icons, MIT.
// Pro: if `bun run icons:pro` has installed Hugeicons Pro into the gitignored pro/ folder, the
// icons the design draws solid come from @hugeicons-pro/core-solid-rounded instead. The rest are
// the same Stroke Rounded icons either way. PR_BUNNY_ICONS=free forces the free set.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const OUT = join(ROOT, "generated", "icons.ts");
export const PRO_PACKAGE = "@hugeicons-pro/core-solid-rounded";
const proDir = join(ROOT, "pro", "node_modules", ...PRO_PACKAGE.split("/"));
if (import.meta.main) {
  const pro = existsSync(proDir) && process.env.PR_BUNNY_ICONS !== "free";

  /** Our name → [free icon, Pro solid icon or null if it's the same in both]. */
  const ICONS: Record<string, [string, string | null]> = {
    inbox: ["InboxIcon", null],
    inboxUnread: ["InboxUnreadIcon", null],
    inboxCheck: ["InboxCheckIcon", null],
    review: ["Audit02Icon", null],
    settings: ["Settings01Icon", null],
    analytics: ["ChartNoAxesCombinedIcon", "ChartNoAxesCombinedIcon"],
    moon: ["Moon02Icon", "Moon02Icon"],
    sun: ["Sun03Icon", "Sun03Icon"],
  };

  const freeNames = [...new Set(Object.values(ICONS).map(([f]) => f))];
  const proNames = [...new Set(Object.values(ICONS).flatMap(([, p]) => (p ? [p] : [])))];
  const lines = [
    "// Generated by packages/icons/scripts/generate.ts. Don't edit; not committed.",
    `import { ${freeNames.map((n) => `${n} as free_${n}`).join(", ")} } from "@hugeicons/core-free-icons";`,
    ...(pro ? [`import { ${proNames.map((n) => `${n} as pro_${n}`).join(", ")} } from "../pro/node_modules/${PRO_PACKAGE}";`] : []),
    "",
    `/** "pro" when Hugeicons Pro is installed locally (bun run icons:pro), else "free". */`,
    `export const ICON_SET: "free" | "pro" = ${JSON.stringify(pro ? "pro" : "free")};`,
    "",
    "export const icons = {",
    ...Object.entries(ICONS).map(([name, [f, p]]) => `  ${name}: ${pro && p ? `pro_${p}` : `free_${f}`},`),
    "};",
    "",
  ];
  const text = lines.join("\n");
  mkdirSync(join(ROOT, "generated"), { recursive: true });
  if (!existsSync(OUT) || readFileSync(OUT, "utf8") !== text) writeFileSync(OUT, text);
  console.log(pro ? "✓ icons: Hugeicons Pro" : "○ icons: Hugeicons free");
}
